#!/usr/bin/env bash

set -e

wget https://telegram.org/dl/desktop/linux
tar xf linux
rm linux
mkdir -p ~/.telegram
sudo mv Telegram/Telegram /usr/local/bin/telegram
sudo mv Telegram/Updater /usr/local/bin/Updater
rm -rf Telegram
