#!/bin/sh

LEIN_VERSION=2.7.1
LEIN_INSTALL=/usr/local/bin

mkdir -p /tmp/lein-install
cd /tmp/lein-install

sudo mkdir -p $LEIN_INSTALL
wget -q https://github.com/technomancy/leiningen/archive/$LEIN_VERSION.tar.gz
echo "876221e884780c865c2ce5c9aa5675a7cae9f215 *$LEIN_VERSION.tar.gz" | sha1sum -c -

mkdir ./leiningen
tar -xzf $LEIN_VERSION.tar.gz  -C ./leiningen/ --strip-components=1
sudo mv leiningen/bin/lein-pkg $LEIN_INSTALL/lein
rm -rf $LEIN_VERSION.tar.gz ./leiningen
sudo chmod 0755 $LEIN_INSTALL/lein

wget -q https://github.com/technomancy/leiningen/releases/download/$LEIN_VERSION/leiningen-$LEIN_VERSION-standalone.zip
wget -q https://github.com/technomancy/leiningen/releases/download/$LEIN_VERSION/leiningen-$LEIN_VERSION-standalone.zip.asc

gpg --keyserver pool.sks-keyservers.net --recv-key 2E708FB2FCECA07FF8184E275A92E04305696D78
gpg --verify leiningen-$LEIN_VERSION-standalone.zip.asc

rm leiningen-$LEIN_VERSION-standalone.zip.asc
sudo mkdir -p /usr/share/java
sudo mv leiningen-$LEIN_VERSION-standalone.zip /usr/share/java/leiningen-$LEIN_VERSION-standalone.jar

